// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vqbblawxuagnzehqtjpb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZxYmJsYXd4dWFnbnplaHF0anBiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQzNzM2MjQsImV4cCI6MjA2OTk0OTYyNH0.mBxBsmLwK4rhzLHIv3dGDiwUjR0NXJg8tHiruXZ_X_k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});